### ISSUE TITLE
Random Empty Loot Window Opening

### ISSUE THREAD

**Issue by 4EverCuber** [dtabacaru/ClamPulp#3]
I'm playing a warlock on the new Anniversary realm (Version 1.15.5.57807). After nearly every action I do, like putting a soul stone on myself for example, an empty loot window opens up that I must close. This only started happening after your latest update to addon. (Game Version 1.15.5).

I'm confident it's related to this addon as I've disabled all my other addons with the exception of this one and when I reload the UI, the empty loot window pops up. 

Please advise. Thank you.

**Comment by 4EverCuber** [comment]
I believe I found the issue. I had some glitched clams in my inventory. Upon deleting them the issue stopped. I apologize for jumping the gun. Great addon you put together. One I've been using since 2019.

**Comment by dtabacaru** [comment]
No problem, let me know if you notice anything again in the future.
